# Generated by Django 2.2.4 on 2019-09-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_app', '0002_auto_20190902_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graymodel',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='graymodel',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
