# Generated by Django 2.2.4 on 2019-09-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_app', '0003_auto_20190902_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceReadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('faceread_image', models.ImageField(default='faceread/faceread.jpg', upload_to='')),
            ],
        ),
    ]
