# Generated by Django 2.2.4 on 2019-09-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_app', '0008_auto_20190904_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graymodel',
            name='gray_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
