# Generated by Django 2.2.4 on 2019-09-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_app', '0009_auto_20190905_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graymodel',
            name='gray_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
