# Generated by Django 2.2.4 on 2019-09-05 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convert_app', '0011_auto_20190905_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graymodel',
            name='gray_image',
            field=models.ImageField(default='output/grayscale/grayscale.jpg', upload_to=''),
        ),
    ]
